### PR TITLE
Fix .gitignore for the analytics project template

### LINKED ISSUE #37: sfdx force:project:create crashing in v47.3.6
### Summary

`sfdx force:project:create`crashes when salesforcedx is in v47.3.6

### Steps To Reproduce:

1.  Update to latest version of sfdx (v47.3.6)
2. Run `sfdx force:project:create -n myProject`

### Expected result

A project is created

### Actual result

The command is crashing with the following error: `AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist`

### Additional information

```
{ AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/lib/templates/project/.gitignore
    at EditionInterface.exports.copy (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at ProjectGenerator.writing (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/lib/generators/projectGenerator.js:72:25)
    at Object.<anonymous> (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/node_modules/yeoman-generator/lib/index.js:395:23)
    at /Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/node_modules/yeoman-generator/lib/index.js:396:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
{ AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/lib/templates/project/.gitignore
    at EditionInterface.exports.copy (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at ProjectGenerator.writing (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/lib/generators/projectGenerator.js:72:25)
    at Object.<anonymous> (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/node_modules/yeoman-generator/lib/index.js:395:23)
    at /Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/fabientaillon/.local/share/sfdx/client/7.30.12-9919bf456f/node_modules/salesforcedx-templates/node_modules/yeoman-generator/lib/index.js:396:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

Plugins versions:
```
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.3.6 (core)
├─ salesforcedx-templates 47.3.1 (core)
└─ salesforce-alm 47.6.0 (core)

sfdx-cli 7.30.12 (core)
```

### PR DESCRIPTION
**Pull request by smithgp**
### What does this PR do?
Renames the `gitignore` file in the project template to `.gitignore` when run via the analytics project template.

### What issues does this PR fix or reference?
Fixes #37

### CODE REVIEW

File: src/generators/projectGenerator.ts [hunk 1]
```diff
@@ -153,9 +153,10 @@ export default class ProjectGenerator extends generator {
         );
       }
       for (const file of filestocopy) {
```
Comment (brpowell) [inline src/generators/projectGenerator.ts]: Thank you for catching this. Going to file a story to clean this command up a bit.
